# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 372934490ff9388eb381e5d764eb2bb11fefbded306dd01ef23b85bcc80d733646a45e99007b42e44d0c8e26dd67fed1bb92b1454977198bda6073e5e5b1554d

test:
  secret_key_base: b63873d7a1325adda4be2c1b1e383c53bb765cc9ffca4102b4f24f2bc59ba6596127fd3e2819a93cbf57a85da04a78f1c119ee2db90c127dbded007f9de6a234

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
